<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/bcs-iitk/BCS_Workshop_Apr_20/blob/master/Python_Tutorial/Python_Tutorial.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/bcs-iitk/BCS_Workshop_Apr_20/blob/master/Python_Tutorial/Python_Tutorial.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://github.com/bcs-iitk/BCS_Workshop_Apr_20/raw/master/Python_Tutorial/Python_Tutorial.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

# Python Tutorial For The BCS Workshop Apr '20
***Author:*** [*Shashi Kant*](http://shashikg.github.io/)

This tutorial is targeted to those, who are not familiar with Python and use of Pyhton for scientific computing. 

## Hello World Example

In [0]:
# This is a comment
print("Helllo World")

## Variables and basic data types

Like other programming languages, Python also have similar basic data types such as integers, float, strings, etc. Unlike in C/ C++, you don't need any additional declaration of variables or their variable type, you can straight away start using. Examples given below will clear it for you. 

### Numbers

In [2]:
# Integers

x = 2 # This will create new integer variable 'x' with value as 2
print(type(x))
print("x is:",x,"and x + 1 is:", x+1) # multiple print statements and addition of two integers
print("x multiply by 3 is:",x*3, "and x^3 is:", x**3) # multiplication and power of
x += 1 # Increment statement
print(x) 

<class 'int'>
x is: 2 and x + 1 is: 3
x multiply by 3 is: 6 and x^3 is: 8
3


In [3]:
# Floats

x = 2.0 # This how you create a new float variable
print(type(x))
print("x is:{} and x + 1 is: {}".format(x,x+1))
print("x multiply by 3 is:",x*3, "and x^3 is:", x**3)
x += 1
print(x)

<class 'float'>
x is:2.0 and x + 1 is: 3.0
x multiply by 3 is: 6.0 and x^3 is: 8.0
3.0


In [4]:
# Type Conversion

x = 2
print(x, type(x))
x += 1.0 # This will convert the integer data type to float data type
print(x, type(x))

2 <class 'int'>
3.0 <class 'float'>


### Strings

string function:
1. s.find(s1): searches for s1 in s and returns the index of first occurence of s1 in s.
2. s.find(s1,initial_index,final_index):searches for s1 in the given range.(returns -1 if not found)
3. s.count(s1): returns number of counts of s1 in s.
4. s.replace(s1,s2): replaces s1 with s2 in string s.

In [25]:
x = "bcs_iitk"
print(type(x))
print(x)
print(len(x))

y = "workshop april 2020"
z = x + " " + y # This is how you concatenate strings
print(z)

<class 'str'>
bcs_iitk
8
bcs_iitk workshop april 2020


### Booleans

In [26]:
x = True
y = False
print(type(x))
print(x and y)
print(x or y)
print(not x)

<class 'bool'>
False
True
False


## Lists and Dictionaries

### Lists 
Lists are container which can contain several elements or values in one variable name. Quite similar to arrays in C/ C++ but with additional features.


List functions:
1. lst.append(obj): appends object at the end permanently.
2. lst.remove(obj): permanently removes from list.
3. del(lst[index]): element at index is deleted.
4. lst.pop(obj): removes obj from the list and also returns it.
5. lst.insert(index,obj)
6. lst.sort(): permanently sorts the list.
7. max/min(lst): returns max/min of the list.

#### Creating lists

In [11]:
x = [5, 1, 8] # Creating a list of 3 elements
print(x)

# Calling individual element
print("1st element:",x[0],"and 1st last element:", x[-1])

# change value
x[1] = 2
print("Change Value:",x)

# Add a new element
x.append(4)
print("new element:",x)

# Removing any element at specified index
print("Removed element:",x.pop(3), "| Left out list:",x)

y = [] # Initialising an empty list
print(y)
y.append(x.pop(0))
print("y:",y, "| x:",x)

[5, 1, 8]
1st element: 5 and 1st last element: 8
Change Value: [5, 2, 8]
new element: [5, 2, 8, 4]
Removed element: 4 | Left out list: [5, 2, 8]
[]
y: [5] | x: [2, 8]


#### Slicing
In python you can easily get the sublists using slicing.

In [16]:
x = [*range(10)] # short trick to create a list containing integers from 0 to 10
y = [*range(2,10,2)]
print(x)
print(y)
print(x[:5]) # from starting index to 4
print(x[5:]) # from 5 to last index
print(x[3:8]) # from 3 to 7
x[:3] = [*range(3,6)] # changing value of a slice
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 4, 6, 8]
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[3, 4, 5, 6, 7]
[3, 4, 5, 3, 4, 5, 6, 7, 8, 9]


In [24]:
x=range(10);
y=[range(10)];
index=1;
value=9;
y.insert(index,value);
y.append(4)
print(y)

[range(0, 10), 9, 4]


'*' is an unpacking operator which unpacks the results of range function.

instances of classes are objects hence range(1,10) is an object of the range class however [range(0,10)] is an object of the list class with range object as one of its element.

### Dictionaries
Dictionary are variables which stores key-value pairs.

In [0]:
# 'Name', 'Branch' and 'Roll' are keys || 'Shashi', 'Electrical' and 160645 are there respective values
student_1 = {'Name': 'Shashi', 'Branch': 'Electrical', 'Roll': 160645}
print(student_1)
print(student_1['Name'])
print(student_1['Roll'])

# Adding new key-value pair
student_1['CPI'] = 'NA' # :-P
print(student_1)

In [27]:
student_1 = {'Name': 'Shashi', 'Branch': 'Electrical', 'Roll': 160645}
for x in student_1.keys():
    print(x," ");
for x in student_1.items():
    print(x," ");
for x in student_1.values():
    print(x," ");

Name  
Branch  
Roll  
('Name', 'Shashi')  
('Branch', 'Electrical')  
('Roll', 160645)  
Shashi  
Electrical  
160645  


## Conditional Statements (if-else)
Conditional statements are used for decision making. Unlike C/C++, there is no switch-case thing in Python.

In [29]:
x = 1

if x == 1:
    print("x is 1")
else:
    print("x is not 1")

x = 2
if x == 1:
    print("x is 1")
else:
    print("x is not 1")
    
x = 2
if x == 1:
    print("x is 1")
elif x == 2: # unlike C/C++ elif is used instead of else if
    print("x is 2")
else:
    print("x is neither 1 nor 2")
    
x = 3
if x == 1:
    print("x is 1")
elif x == 2:
    print("x is 2")
else:
    print("x is neither 1 nor 2")

x is 1
x is not 1
x is 2
x is neither 1 nor 2


## Loops
Loops are used to run same kind of lines multiple times.

In [30]:
# general loop
for i in range(5):
    print(i)

print('------')
for i in range(1, 8, 2):#range(initial,final,ksteps):starts from initial value till final-1(or before) with ksteps at a time
    print(i)

0
1
2
3
4
------
1
3
5
7


In [32]:
# Looping over a list
x = [2, 5, 6]
for i in x:
    print(i)

2
5
6


In [33]:
# list comprehension
x = [*range(5)]
x_sq = [i ** 2 for i in x]
print(x)
print(x_sq)

[0, 1, 2, 3, 4]
[0, 1, 4, 9, 16]


In [34]:
# while loop
x = 1
while x<5:
    print(x)
    x+=1

1
2
3
4


## Functions
Defined simply using ```def``` keyword. Can return as many variable as much you want. Can take optional keyword arguments as well.

In [35]:
# simple python function
def poly(poly_idx, x):
    value = 0
    l = len(poly_idx) - 1
    
    for i in range(l+1):
        value += poly_idx[i]*(x**(l-i))
        
    return value

print("x^2 + x + 1 at x = 0 is:", poly([1, 1, 1], 0))
print("x^2 + x + 1 at x = 1 is:", poly([1, 1, 1], 1))
print("x^2 + x + 1 at x = 2 is:", poly([1, 1, 1], 2))
print("2x^2 + x + 1 at x = 2 is:", poly([2, 1, 1], 1))

x^2 + x + 1 at x = 0 is: 1
x^2 + x + 1 at x = 1 is: 3
x^2 + x + 1 at x = 2 is: 7
2x^2 + x + 1 at x = 2 is: 4


Keword arguments or 'named' arguments are common to python unlike many other programming languages. Eg- in C formal parameters recieve the value of actual parameters through paramter passing. In python also this is parameter passing is present. Apart from this another method of name passing is also present.
1. parameter passing- poly([1,1,1],0)
2. Name passing- poly(poly_idx=[1,1,1],x=0) || poly(x=0,poly_idx=[1,1,1]) when passed by name position of arguments does not matter.
INFERENCE: unlike other programming languages python knows the name of the arguments(i.e. poly_idx,x in above case) our function accepts.

In [36]:
# function which can return multiple var
def get_data():
  return 1, 2, 3

x, y, z = get_data()

print(x, y, z)

1 2 3


In [37]:
# function with optional keyword argument ;read the above marked down cell 
def greet(to_whom, greet_type="Hi"):
  print(greet_type, "Shashi!")

greet("Shashi")
greet("Shashi", greet_type="Bye")

Hi Shashi!
Bye Shashi!


## Classes

Arguments passed to __init__ (apart from self) have to be passed through the class title while object instantiation.
if don't want this then use setter getter methods in which argumnets are passed in functions themselves.

In the proceeding example name and roll are data attributes(variables bound to an object).
get_roll() and greet() are method attributes(methods bound to an object).

In [51]:
class Person():
    def __init__(self, name, roll):## SELF CAN BE CONSIDERED AS A POINTER POINTING TO THE POSITION OF THE INSTANCE OF THE CLASS
        self.name = name
        self.roll = roll
        
    def get_roll(self):
        return self.roll
    
    def greet(self, say_hi_bye="Hi"):
        print(say_hi_bye, self.name) 
        
p1 = Person(name="Shashi",roll=160645)

print(p1.roll)
p1.greet()
p1.greet(say_hi_bye="Bye")

160645
Hi Shashi
Bye Shashi


SETTER/GETTER METHODS

In [53]:
class Person():
    def set_name(self,name):
        self.name=name;
    def get_name(self):    
        return self.name
    
    def set_roll(self,roll):
        self.roll=roll
    def get_roll(self):    
        return self.roll
        
p1 = Person()
p1.set_name("Nakul");
p1.set_roll("180455");
print(p1.get_name(),p1.roll)

Nakul 180455


## Practice Assignment - 1 [Not graded]

### Try creating merge sort algorithm



Pseudo code is given below:

```
// SRC: https://www.geeksforgeeks.org/merge-sort/

MergeSort(arr[], l,  r)
If r > l
     1. Find the middle point to divide the array into two halves:  
             middle m = (l+r)/2
     2. Call mergeSort for first half:   
             Call mergeSort(arr, l, m)
     3. Call mergeSort for second half:
             Call mergeSort(arr, m+1, r)
     4. Merge the two halves sorted in step 2 and 3:
             Call merge(arr, l, m, r)
```

In [0]:
# Write your code here

## SciPy
It contains a collection of python packages for mathematics, science and egineering. We will be covering some of the basics of some of the important packages: **NumPy** and **Matplotlib**

### NumPy

#### General

In [54]:
import numpy as np # this is how you import libraries in Python

In [63]:
# creating numpy arrays
x = np.asarray([3, 1, 5])
print(x)
print(x.shape);
print(x[1])
print(x[:2])

print(np.asarray([[1, 2],[3, 4]]))

[3 1 5]
(3,)
1
[3 1]
[[1 2]
 [3 4]]


In [64]:
x = np.random.random((2,2)) #random 2x2 array
print(x.shape)
print(x)
print(x[1,1])

(2, 2)
[[0.89815623 0.86196051]
 [0.84476346 0.88434695]]
0.8843469492127813


In [65]:
x = np.arange(16) #linear array with values ranging from 0 to 15
print(x)
x = x.reshape((4,4)) #reshaping
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [68]:
# indexing
y = x[:2, 1:]
print(y.shape)
print(y)
print(y.shape[0], y.shape[1])

(2, 3)
[[1 2 3]
 [5 6 7]]
2 3


In [0]:
# boolean indexing
x = np.arange(8)
print(x)
print(x>5)
print(x[x>5])

#### Broadcasting

In [0]:
# Broadcasting 

x = np.asarray([1, 4, 9, 16])
y = np.ones(4,)

## Adding 1

# Usual way
print(x+y)
# broadcasting
print(x+1)

In [0]:
x = np.asarray([[1, 2], [3, 4]])
y = np.asarray([[2], [2]])

print(x)
print(y)

In [0]:
print(x*2) #multiplied to all the indexes

In [0]:
print(x*y) #again mulptiplication

In [0]:
print(np.dot(x, y)) #dot product

In [0]:
print(y.shape)
print(y.T.shape) # transpose

### MatplotLib

In [0]:
import matplotlib.pyplot as plt # creating a shorthand name for the imported library

In [0]:
x = np.arange(0, 6 * np.pi, 0.2)
ys = np.sin(x)
yc = np.cos(x)

plt.plot(x, ys)
plt.plot(x, yc)
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.title('Sin and Cos Curve')
plt.legend(['Sin', 'Cos'])
plt.grid()

### SciPy Stats
Those who don't have any backgrounds in statistics can get back here after completing the stats lecture.

In [0]:
import scipy.stats

rv = scipy.stats.norm(0, 1) # getting a normal random var of mean=0 and var=1

In [0]:
samples = rv.rvs(10000) # taking a random sample
print(samples)
print(samples.shape)

In [0]:
x = np.arange(-4, 4, 0.05)
print(x.shape)
y = rv.pdf(x) #will give the probability distribution function of the random var 'rv'
print(y.shape)

In [0]:
temp = plt.hist(samples, density=True, bins=100) # plot histogram i.e. frequency dist
plt.plot(x, y, 'r-', lw=3)

In [0]:
# An another example with mean=5 and var=1
rv = scipy.stats.norm(5, 1)
samples = rv.rvs(10000)
x = np.arange(0, 10, 0.05)
y = rv.pdf(x)
temp = plt.hist(samples, density=True, bins=100)
plt.plot(x, y, 'r-', lw=3)

In [0]:
# An another example with mean=0 and var=3
rv = scipy.stats.norm(0, 3)
samples = rv.rvs(10000)
x = np.arange(-5, 5, 0.05)
y = rv.pdf(x)
temp = plt.hist(samples, density=True, bins=100)
plt.plot(x, y, 'r-', lw=3)

# For further reference


*   [A Byte of Python](https://python.swaroopch.com/)
*   [NumPy Quickstart Tutorial](https://numpy.org/devdocs/user/quickstart.html#further-reading)
*   [Scipy Lecture Notes](https://numpy.org/devdocs/user/quickstart.html#further-reading)

